version: 2.1

jobs:
  sync-job:
    docker:
      - image: cimg/base:2025.02
    steps:
      - checkout
      - run: echo "I am running a job"

  run-on-main-job:
    docker:
      - image: cimg/base:2025.02
    steps:
      - checkout
      - run: echo "Running on main branch"

  should-only-run-on-specific-conditions:
      docker:
      - image: cimg/base:2025.02
      steps:
      - checkout
      - run: echo "only run on specific conditions"

workflows:
  pr-sync-event:
    when: pipeline.event.action == "synchronize"
    jobs:
      - sync-job
  run-on-main:
    when: pipeline.git.branch == "main"
    jobs:
      - run-on-main-job
  run-on-pr:
    when:
      or:
        - << pipeline.event.name >> == "pull_request" and << pipeline.event.action >> == "labeled"
        - << pipeline.event.name >> == "pull_request" and << pipeline.event.action >> == "synchronize"
    jobs:
      - should-only-run-on-specific-conditions
