version: 2.1

jobs:
  hello-job:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - run: echo "TRIGGER REPO"

workflows:
  my-workflow:
    jobs:
      - hello-job
  tagged-build:
    jobs:
      - hello-job:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
