version: 2.1

jobs:
  sync-job:
    docker:
      - image: cimg/base:2025.02
    steps:
      - checkout
      - run: echo "I am running a job"

  run-on-main-job:
    docker:
      - image: cimg/base:2025.02
    steps:
      - checkout
      - run: echo "Running on main branch"

workflows:
  pr-sync-event:
    when: pipeline.event.action == "synchronize"
    jobs:
      - sync-job
  run-on-main:
    when: pipeline.git.branch == "main"
    jobs:
      - run-on-main-job
